// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAt3hYwGm6ZbcPpeORLX8WhL43jSECKuJo',
    appId: '1:727503229020:android:86edbd4a0b22722f0dd699',
    messagingSenderId: '727503229020',
    projectId: 'jsskos-8852b',
    storageBucket: 'jsskos-8852b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUe2nBhMKImTfkTLJ02dSdUBTMUKdnqqU',
    appId: '1:727503229020:ios:43dc803ced0bbafc0dd699',
    messagingSenderId: '727503229020',
    projectId: 'jsskos-8852b',
    storageBucket: 'jsskos-8852b.appspot.com',
    androidClientId: '727503229020-e3jk60063k10rv5mgemlht2jnhn858iq.apps.googleusercontent.com',
    iosClientId: '727503229020-kbed0lth1ll2r9417tcsf65020smedtk.apps.googleusercontent.com',
    iosBundleId: 'com.example.jsskosApp',
  );
}
